### ISSUE TITLE
Add a way to consolidated printing PDFs/labels

### ISSUE THREAD

**Issue by tdegrunt** [entdec/papyrus#9]
# Why

When multiple prints happen during one request, they need to be consolidated, currently if you receive 20 containers, there will about 10 labels not printed, this applies purely to the data going to printnode.

All PDF's need to be consolidated in one big PDF.
All liquid/ZPL also need to be consolidated in one big ZPL/text file

# Functional

One way to do this is to start papyrus in a consolidated mode at the start of a (particular) request. 
When this consolidated mode is started, papyrus will then generate papers, but not print them.
Then when the consolidation mode is ended at the end of a (particular) request, all paperwork needs to be combined and printed.

The generated paperwork should still be separate paperwork on the order/shipment/etc. 

# Technical 

For this to work every the `Papyrus` class needs a getter setter for this with a consolidation_id (string), we'll likely use the `Praesens.request_id` for this. Also check `Praesens` for how one can store the consolidation_id on the `Papyrus` class.
I'd suggest we do something like this:

```ruby
Papyrus.start_consolidation(Praesens.request_id)
# Do the normal application business logic here
Papyrus.end_consolidation
```

All paperwork generated should store the `consolidation_id` on the paper record. Once consolidation ends, pull (select) all paperwork with the current `consolidation_id` and the same `owner` and `kind` and consolidate it and then send it to printnode. 

For the PDF's we will need to combine the PDF's: https://github.com/boazsegev/combine_pdf
(this seems to be a ruby native solution)

**Comment by plummip** [comment]
Papyrus has to be updated.

**Comment by sanderhelsloot** [comment]
# Container label

- Receive PO
Receiving a Purchase Order in new packing material will generate multiple container labels if the number of packages field is used. Number of Packages 20 and qty 1. Expected result it prints 20 container labels.

> While printing, it had difficulties printing these labels and after the 10th label it got stuck, it printed one label divided on two labels. Using the manual feed button 3 times to print all twenty worked. But this is something we need to look into as it seems to doesn't look like it is able to print 20 labels in one transaction.

The rest of the paperwork I honestly don't know how the enduser prints these documents in one transaction, other then updating the template and change the 'Copies' value.

So still to be tested is:

Commercial invoice, Pack list, Parcel Pack list, Pre packlist, Parcel pack list, Serial list and Tote label.
Please advice how this can be tested.

Talked to Joyie and he mentioned, it only is applied to the Inventory Adjust

1. A label is printed when container is created
2. A label is printed when inventory is adjusted

Scenario 1 cannot be tested as there is no packing material field available for the inventory adjust and scenario 2 failed the test, it did not generated a new label.

Don't know if these two scenarios account for the changes applied printing consolidated.
Moving this ticket back to follow up.

**Comment by sanderhelsloot** [comment]
For clarification as discussed with @tdegrunt this morning, this functionality is only implemented for the Inventory Adjust Upload #2879, where by consolidated printing should work generating new container labels.

The test cases above are not relevant and this is not implemented for the Inventory Adjust manual option.
Added to that, no new container labels will be printed if inventory is adjusted for an existing container. This means the testcase "failed" scenario is actually a "pass".

Besides it is only implemented for the Import, we might want apply this consolidated printing functionality for the (PO) receive option as well, whereby we try generate multiple containers (in one transaction) using the packaging field. This fails to work in using the current functionality.

**Comment by sanderhelsloot** [comment]
Again, not sure what is fixed exactly, but reading the history of this ticket I assume the functionality to print consolidated labels is applied to the PO receive and Import Inventory adjust.

Testing the label printer.

1. Printed a new tote label just fine.
2. Printed a new container label just fine (using the create container option)

**PO Receive**
- Receiving inventory through a PO created a container, but did not printed the label 👎 

Import Inventory Adjust

**Import Adjust Inventory
- Importing this file [adjust inventory consolitated printing.xlsx](https://github.com/entdec/papyrus/files/11664231/adjust.inventory.consolitated.printing.xlsx) and printed all 30 container labels just fine (tested twice). 👍 


I see there are some tickets merged for the PO Receive as well, therefor moving this ticket back to followup as printing new containers during po receive is not working.

**Comment by plummip** [comment]
Papyrus has been updated. And oms with the latest version. We just need to deploy staging.
Fingers crossed that this fixes the problem.

Created a purchase order throught the UI and did multiple receives in 1 request.
For every paper that was printed the consolidation id was put on the paper.
Afterwards a print was done using the ConsolidationSpoolJob.
This job combines and then  prints all the papers with a specific consolidation id.

**Comment by sanderhelsloot** [comment]
Printing a container label on PO receive is not working.
Contacting Joyie directly to see if we can fix the issue on the fly.

**Comment by sanderhelsloot** [comment]
Printing multiple labels with the inventory adjust is no longer working.
Printing labels while receiving a PO is not yet resolved.

Moving this ticket back to follow up and informed Joyie.

**Comment by sanderhelsloot** [comment]
Trying to receive a purchase order for 1 unit I a new (packing material) container.
The receive is successful, but it doesn't print the label.
Reprinting the label (not working from the container show papers tab) from the [papers overview](https://oms.staging.boxture.com/papers/?template_id=004476ac-6029-466b-bb35-57e14144f8d6) it is printing a label showing a qty 0, no part number or description. This is incorrect.
See the link of the container [here](https://oms.staging.boxture.com/containers/59af54d3-e5fc-4a4a-8511-41763bbb7690) and click on the preview button to see the label.

**Comment by sanderhelsloot** [comment]
As discussed with Joyie, for the Po Receive, two items remaining an issue:

1. The correct info is not printed (qty 0 / product info missing) - async issue
2. It is not possible to reprint from the Show container - consolidated id missing

**Comment by tdegrunt** [comment]
1. Indicates the moment of printing may not be correct? Perhaps a better idea for consolidation - to fix the problems we have with this is as follows: We create a paper record with a consolidation_id at the moment the paperwork is asked for (say Container#create), then when we end the consolidation, we go over all papers for the consolidation and generate the paperwork (actually creating the labels/pdfs etc), not printing them, but combining them in a print. 
2. If this is reprinting an individual container label, which was part of a consolidation (ie receive). When doing that we should always print, perhaps using an `manual: true` option? This `manual: true` should also override the conditions on the label.

**Comment by sanderhelsloot** [comment]
Tested it all again.

Inventory adsjust
1. The inventory adjust, this printed the labels for EMOE and METER using the parent account WRAP-IT
2. The inventory adjust, printed 30 labels consolidated, perfectly fine.
3. The reprint is working fine from the papers screen and from the papers tab from the container show
4. The consolidated reprint is working fine from the papers screen and the papers tab from the container show

po receive
1. received 1 packing material and printed one container label
2. reprinted this from the container show and the papers overview
3. received 100 inventory items devided over 10 packages and printed 10 container labels successfully
4. reprinted the individual label (1 label) just fine
5. reprinted consolidated (10 labels) just fine

This means that the printing using the consolidation functionality is implemented successful and item 1 and 2 have been resolved.

Closing this ticket.
